### ISSUE TITLE
Please give a code to implement and intialize the tracker object in python code

### ISSUE THREAD

**Issue by abhinavisgood** [derkbreeze/LPT#1]
Would you guide me over how i should  implement this in the code using some othe object detector give output in the form of [ [x1, y1, x2, y2 , conf_score1 ]  ,  [  x12 , y12, x22, y22 , conf_score2 ]     . . . ]  and i want some way through which i would be able to implement this output into a tracker object and utilize it  and get an  output in format of bounding  [tracker_id : bbox]

thanks in advance

**Comment by derkbreeze** [comment]
Hi,

If you want to perform inference using other detections, you need to extract your own ReID features in [https://github.com/KaiyangZhou/deep-person-reid](url). the features should be in accordance with the order of detections in MOT17 format,e.g. [[frame1, -1, x1, y1, w1, h1, conf_score], [frame1, -1, x2, y2, w2, h2, con_score], ...[frame_t, -1, xt, yt, wt, ht, conf_score]].

The initialization of Tracker class has nothing to do with specific detector inputs. It solely uses a trained MLP for initialization. After downloading the trained model, you can play with your own detector by changing the input in this part in run_test.ipynb.

`det_file = './data/_{}/det_{}.txt'.format(sequence, detector)
`
`app_file = './data/_{}/app_det_{}.npy'.format(sequence, detector)
`
`dets = np.loadtxt(det_file, delimiter=',')
`
`app_feats = np.load(app_file)
`

Hope it helps.

**Comment by abhinavisgood** [comment]
I'm trying to implment it on a video camera , which can be my laptop webcam and afterwords can be a real camera
